# Generated by Django 2.2.9 on 2020-02-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was created', verbose_name='created_at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date time on wich the object was updated', verbose_name='updated at')),
                ('text_comment', models.TextField()),
                ('image_comment', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was created', verbose_name='created_at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date time on wich the object was updated', verbose_name='updated at')),
                ('image_post', models.ImageField(blank=True, null=True, upload_to='')),
                ('text_post', models.TextField()),
                ('feeling', models.CharField(max_length=50)),
                ('ubication', models.CharField(blank=True, max_length=100, null=True)),
                ('is_private', models.BooleanField(default=False, help_text='True if user wants the post its private.', verbose_name='private')),
            ],
            options={
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
