# Generated by Django 2.2.9 on 2020-02-17 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20200217_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was created', verbose_name='created_at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date time on wich the object was updated', verbose_name='updated at')),
                ('short_name', models.CharField(max_length=50)),
                ('image_reaction', models.ImageField(blank=True, null=True, upload_to='reactions/pictures')),
            ],
            options={
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='image_comment',
            field=models.ImageField(blank=True, null=True, upload_to='posts/pictures'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_post',
            field=models.ImageField(blank=True, null=True, upload_to='posts/pictures'),
        ),
        migrations.CreateModel(
            name='ReactionAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was created', verbose_name='created_at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date time on wich the object was updated', verbose_name='updated at')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Reaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='post',
            name='reactions',
            field=models.ManyToManyField(through='posts.ReactionAssignment', to='posts.Reaction'),
        ),
    ]
